// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCx2x6byQulUrycDROTvzza-4ZTekVpfHo',
    appId: '1:1062271216788:web:472eb9cf9e2c6f22b75881',
    messagingSenderId: '1062271216788',
    projectId: 'traer-40850',
    authDomain: 'traer-40850.firebaseapp.com',
    storageBucket: 'traer-40850.appspot.com',
    measurementId: 'G-D9B0WHNN3D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0_t4q8YGukio-NPO6tJPib54AXJYFJsk',
    appId: '1:1062271216788:android:e4de51553fd8aedab75881',
    messagingSenderId: '1062271216788',
    projectId: 'traer-40850',
    storageBucket: 'traer-40850.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9EZG93Yfn85EjgrFZaqZQgYrFjPgEYbw',
    appId: '1:1062271216788:ios:1e37e827bb43f5afb75881',
    messagingSenderId: '1062271216788',
    projectId: 'traer-40850',
    storageBucket: 'traer-40850.appspot.com',
    iosBundleId: 'com.traer.app.traer',
  );
}
